//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDLA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tasks()
        {
            this.TaskAssigns = new HashSet<TaskAssigns>();
        }
    
        public int ID { get; set; }
        public int ListID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int Completed { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int Creator { get; set; }
        public System.DateTime LastChange { get; set; }
        public int ChangedBy { get; set; }
    
        public virtual ToDoLists ToDoLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskAssigns> TaskAssigns { get; set; }
    }
}
